# Generated by Django 5.0.3 on 2024-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='philhealth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
