# Generated by Django 5.0.3 on 2024-04-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_payslip_philhealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='philhealth',
        ),
    ]
