# Generated by Django 5.0.2 on 2024-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_remove_payslip_philhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.FloatField(max_length=255),
        ),
    ]
