# Generated by Django 5.0.3 on 2024-05-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_alter_payslip_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
