apiVersion: apps/v1
kind: Deployment
metadata:
  name: Lazapee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Lazapee
  template:
    metadata:
      labels:
        app: Lazapee
    spec:
      containers:
        - name: my-container
          image: halleyscomet0855/lazapee

          ports:
            - containerPort: 8080
