apiVersion: v1 # first step: create a ClusterIP service for the mysql container
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
---
apiVersion: v1 # second step: create a PV claim. according to lab, claiming a PV should be enough.
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # 3rd step: deploy a mysql pod.
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest # should retrieve a mysql image
          name: mysql
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
          volumeMounts:
            - name: mysql-persistent-storage # This mounts the volume to a path: mysql will use mountPath
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim # binds the volume to the PVC.
