apiVersion: v1
kind: Service
metadata:
  name: service-lazapee
spec:
  type: LoadBalancer
  # loadBalancerIP: xx.xx.xxx
  selector:
    app: lazapee
  ports:
    - name: service-lazapee
      port: 8080
      targetPort: 8080
